{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "name" . | quote }}
  namespace: {{ include "namespace" . }}
  labels:
    {{- toYaml .Values.serviceMonitor.labels | nindent 4}}
spec:
  endpoints:
  - port: {{ .Values.service.name }}
    interval: 60s
  namespaceSelector:
    matchNames:
    - {{ .Values.namespace }}
  selector:
    matchLabels:
{{ include "common-labels" . | indent 6 }}
{{- end -}}
