---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{- include "kubenurse.serviceAccountName" . | nindent 4 }}
  labels:
    {{- include "kubenurse.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
