{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kubenurse.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubenurse.labels" . | nindent 4 }}
    {{- if .Values.serviceMonitor.labels }}
    {{- toYaml .Values.serviceMonitor.labels | nindent 4}}
    {{- end }}
spec:
  endpoints:
  - port: {{ .Values.service.name }}
    interval: 60s
    {{- with .Values.serviceMonitor.relabelings }}
    relabelings:
    {{- toYaml . | nindent 6 }}
    {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
    {{- include "kubenurse.selectorLabels" . | nindent 6 }}
{{- end -}}
