---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
    app: {{ include "name" . | quote }}
{{ include "common-labels" . | indent 4 }}
  name: {{ include "name" . | quote }}
  namespace: {{ include "namespace" . }}
spec:
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ include "name" . | quote }}
