---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubenurse.fullname" . }}
  labels:
    {{- include "kubenurse.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "kubenurse.selectorLabels" . | nindent 4 }}
