{
 "title": "Kubenurse",
 "description": "Kubenurse network monitoring",
 "tags": [
  "kubernetes",
  "k8s",
  "network"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kubernetes_cluster_name)"
    }
   },
   {
    "name": "request_type",
    "label": "Request",
    "query": "api_server_direct, api_server_dns, me_service, me_ingress, path_"
   }
  ]
 },
 "panels": [
  { "title": "$request_type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "request_type" },
  {
   "title": "Requests $request_type",
   "type": "heatmap",
   "description": "Latency heatmap for $request_type requests",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(kubenurse_httpclient_request_duration_seconds_bucket{kubernetes_cluster_name=~\"$cluster\", type=~\"$request_type.*\"})) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Error rate $request_type",
   "type": "timeseries",
   "description": "Error rate for $request_type type",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(kubenurse_errors_total{type=~\"$request_type.*\",kubernetes_cluster_name=\"$cluster\"}[5m])",
     "legendFormat": "errors_{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum (irate(kubenurse_errors_total{type=~\"$request_type.*\",kubernetes_cluster_name=\"$cluster\"}[15m]))",
     "legendFormat": "Sum over all pods"
    }
   ]
  },
  {
   "title": "http request duration by Pod (p0.95)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(kubenurse_httpclient_request_duration_seconds_bucket{kubernetes_cluster_name=\"$cluster\", type=~\"$request_type.*\"}) by (le, pod))",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "http request tracing (p0.95)",
   "type": "timeseries",
   "description": "Time in seconds since the start of the http request to complete the action. This is a useful chart to further debug connection issues.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(kubenurse_httpclient_trace_request_duration_seconds_bucket{kubernetes_cluster_name=\"$cluster\",type=~\"$request_type.*\"}) by (le, event))",
     "legendFormat": "{{ event }}"
    }
   ]
  },
  { "title": "Shared information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "DNS duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(kubenurse_httpclient_trace_request_duration_seconds_bucket{kubernetes_cluster_name=\"$cluster\",event=\"dns_done\"}) by (le))\n-\nhistogram_quantile(0.95, sum(kubenurse_httpclient_trace_request_duration_seconds_bucket{kubernetes_cluster_name=\"$cluster\",event=\"dns_start\"}) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  { "title": "Debug information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "http requests by Pod",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum (kubenurse_httpclient_requests_total{kubernetes_cluster_name=\"$cluster\"}) by (pod, kubernetes_node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_cluster_name=\"$cluster\", app_kubernetes_io_name=\"kubenurse\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app_kubernetes_io_name=\"kubenurse\", kubernetes_cluster_name=\"$cluster\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Open FDS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "process_open_fds{kubernetes_cluster_name=\"$cluster\", app_kubernetes_io_name=\"kubenurse\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}